"""Data-workstream Phase 1 ingest and validation entrypoints."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from typing import Iterable

import pandas as pd

from .join_keys import REQUIRED_JOIN_KEYS
from .manifest_models import DatasetManifest, ManifestProvenance
from .pandera_schemas import (
    validate_embedding_frame,
    validate_play_metadata_frame,
    validate_tracking_frame,
)


@dataclass(frozen=True, slots=True)
class GameIngestArtifacts:
    season: int
    week: int
    game_id: str
    lake_root: Path
    manifest_paths: tuple[Path, ...]


@dataclass(frozen=True, slots=True)
class SeasonIngestSummary:
    season: int
    ingested_games: int
    lake_root: Path
    manifest_paths: tuple[Path, ...]


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _schemas_package_root() -> Path:
    return Path(__file__).resolve().parents[2]


def default_curated_fixture_dir() -> Path:
    return _schemas_package_root() / "fixtures" / "datasets" / "bigdatabowl_2023"


def default_lake_root() -> Path:
    return _schemas_package_root() / "fixtures" / "lake"


def _read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, keep_default_na=True)


def _manifest_version(base_version: str, season: int, week: int, game_id: str) -> str:
    normalized = base_version.replace("/", "-").replace(" ", "-")
    return f"{normalized}-s{season}-w{week}-{game_id}"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _ensure_join_keys(
    frame: pd.DataFrame,
    *,
    nullable_join_keys: Iterable[str],
) -> pd.DataFrame:
    normalized = frame.copy()
    nullable = set(nullable_join_keys)
    for key in REQUIRED_JOIN_KEYS:
        if key not in normalized.columns:
            normalized[key] = pd.NA

    required_non_null = [key for key in REQUIRED_JOIN_KEYS if key not in nullable]
    missing_values = [
        key
        for key in required_non_null
        if normalized[key].isna().any()
    ]
    if missing_values:
        raise ValueError(
            "Join-key validation failed: non-null keys contain missing values: "
            + ", ".join(sorted(missing_values))
        )
    return normalized


def _write_parquet(frame: pd.DataFrame, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(output_path, index=False, engine="pyarrow")


def _write_manifest(
    *,
    lake_root: Path,
    dataset: str,
    dataset_version: str,
    schema_version: str,
    source: str,
    season: int,
    week: int,
    game_id: str,
    model_version: str | None,
    payload_schema_version: str,
    row_count: int,
    checksum: str,
    created_by: str,
    source_uri: str,
    artifact_path: Path,
) -> Path:
    manifest = DatasetManifest(
        dataset=dataset,
        dataset_version=dataset_version,
        schema_version=schema_version,
        source=source,
        season=season,
        week=week,
        game_id=game_id,
        model_version=model_version,
        payload_schema_version=payload_schema_version,
        row_count=row_count,
        checksum=checksum,
        created_at=datetime.now(timezone.utc),
        created_by=created_by,
        provenance=ManifestProvenance(
            run_id=None,
            source_uri=source_uri,
            notes="Generated by Data Phase 1 ingest flow.",
            extra={"artifact_path": artifact_path.as_posix()},
        ),
    )

    manifest_path = (
        lake_root
        / "manifests"
        / dataset
        / f"{dataset_version}.json"
    )
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(manifest.model_dump_json(indent=2), encoding="utf-8")
    return manifest_path


def _build_processed_plays_frame(
    *,
    plays: pd.DataFrame,
    source: str,
    payload_schema_version: str,
    fallback_dataset_version: str,
    fallback_model_version: str,
) -> pd.DataFrame:
    frame = plays.copy()
    frame = frame.rename(columns={"team_context_id": "team_id"})
    frame["source"] = source
    frame["frame_id"] = None
    frame["player_id"] = pd.NA
    frame["dataset_version"] = frame.get("dataset_version", fallback_dataset_version).fillna(
        fallback_dataset_version
    )
    frame["model_version"] = frame.get("model_version", fallback_model_version).fillna(
        fallback_model_version
    )
    frame["payload_schema_version"] = payload_schema_version

    keep_columns = [
        "source",
        "season",
        "week",
        "game_id",
        "play_id",
        "frame_id",
        "player_id",
        "team_id",
        "model_version",
        "dataset_version",
        "payload_schema_version",
        "raw_play_id",
        "offense_team_abbr",
        "defense_team_abbr",
        "dci",
        "dis",
        "explosive_gain_yards",
        "expected_points_added",
        "pass_result",
        "play_description",
        "game_date_iso",
    ]
    frame = frame[keep_columns]
    frame = _ensure_join_keys(frame, nullable_join_keys={"frame_id", "player_id"})
    return validate_play_metadata_frame(frame)


def _build_tracking_frame(
    *,
    dataset_dir: Path,
    dataset_manifest: dict[str, object],
    all_plays: pd.DataFrame,
    season: int,
    week: int,
    game_id: str,
    source: str,
    payload_schema_version: str,
    dataset_version: str,
    model_version: str,
) -> pd.DataFrame:
    team_lookup = (
        all_plays[["play_id", "team_context_id"]]
        .drop_duplicates(subset=["play_id"])
        .set_index("play_id")["team_context_id"]
        .astype(str)
        .to_dict()
    )

    rows: list[pd.DataFrame] = []
    for sample in dataset_manifest.get("motion_samples", []):
        if str(sample.get("game_id")) != game_id:
            continue

        sample_path = dataset_dir / str(sample["path"])
        if not sample_path.exists():
            continue

        sample_frame = _read_csv(sample_path)
        sample_frame["source"] = source
        sample_frame["season"] = season
        sample_frame["week"] = week
        sample_frame["dataset_version"] = dataset_version
        sample_frame["model_version"] = model_version
        sample_frame["payload_schema_version"] = payload_schema_version
        sample_frame["player_id"] = sample_frame["nfl_id"].astype(str)
        sample_frame["team_id"] = sample_frame["play_id"].map(team_lookup)
        rows.append(sample_frame)

    if not rows:
        columns = [
            "source",
            "season",
            "week",
            "game_id",
            "play_id",
            "frame_id",
            "player_id",
            "team_id",
            "model_version",
            "dataset_version",
            "payload_schema_version",
            "x",
            "y",
            "node_stress",
            "frame_dci",
            "frame_dis",
            "player_label",
            "player_position",
            "player_side",
        ]
        return pd.DataFrame(columns=columns)

    frame = pd.concat(rows, ignore_index=True)
    frame = frame[
        [
            "source",
            "season",
            "week",
            "game_id",
            "play_id",
            "frame_id",
            "player_id",
            "team_id",
            "model_version",
            "dataset_version",
            "payload_schema_version",
            "x",
            "y",
            "node_stress",
            "frame_dci",
            "frame_dis",
            "player_label",
            "player_position",
            "player_side",
        ]
    ]
    frame = _ensure_join_keys(frame, nullable_join_keys=set())
    return validate_tracking_frame(frame)


def _build_embedding_frame(
    *,
    processed_plays: pd.DataFrame,
) -> pd.DataFrame:
    frame = processed_plays[
        [
            "source",
            "season",
            "week",
            "game_id",
            "play_id",
            "frame_id",
            "player_id",
            "team_id",
            "model_version",
            "dataset_version",
            "payload_schema_version",
            "dci",
            "dis",
        ]
    ].copy()
    frame["embedding_dim"] = 2
    frame["embedding_0"] = frame["dci"].fillna(0.0)
    frame["embedding_1"] = frame["dis"].fillna(0.0)
    frame = frame.drop(columns=["dci", "dis"])
    frame = _ensure_join_keys(frame, nullable_join_keys={"frame_id", "player_id"})
    return validate_embedding_frame(frame)


def ingest_game(
    *,
    game_id: str,
    season: int | None = None,
    dataset_dir: str | Path | None = None,
    lake_root: str | Path | None = None,
    source: str = "nfl_big_data_bowl",
    payload_schema_version: str = "0.0.1",
    schema_version: str = "0.0.1",
    created_by: str = "data-workstream-phase1",
) -> GameIngestArtifacts:
    """Ingest and validate one game from curated fixture data into canonical lake paths."""

    _ = _repo_root()  # Anchors path resolution to workspace layout in editable installs.
    resolved_dataset_dir = (
        Path(dataset_dir).resolve() if dataset_dir is not None else default_curated_fixture_dir()
    )
    resolved_lake_root = (
        Path(lake_root).resolve() if lake_root is not None else default_lake_root()
    )

    dataset_manifest = _read_json(resolved_dataset_dir / "manifest.json")
    dataset_version = str(dataset_manifest["dataset_version"])
    model_version = str(dataset_manifest["model_version"])

    games = _read_csv(resolved_dataset_dir / "games.csv")
    plays = _read_csv(resolved_dataset_dir / "plays.csv")

    selected_games = games[games["game_id"].astype(str) == game_id].copy()
    if season is not None:
        selected_games = selected_games[selected_games["season"].astype(int) == season]
    if selected_games.empty:
        raise ValueError(f"Game '{game_id}' was not found in the curated fixture dataset.")

    resolved_season = int(selected_games.iloc[0]["season"])
    resolved_week = int(selected_games.iloc[0]["week"])

    selected_plays = plays[
        (plays["game_id"].astype(str) == game_id)
        & (plays["season"].astype(int) == resolved_season)
    ].copy()
    if selected_plays.empty:
        raise ValueError(
            f"No play rows were found for game '{game_id}' in season {resolved_season}."
        )

    processed_plays = _build_processed_plays_frame(
        plays=selected_plays,
        source=source,
        payload_schema_version=payload_schema_version,
        fallback_dataset_version=dataset_version,
        fallback_model_version=model_version,
    )

    tracking = _build_tracking_frame(
        dataset_dir=resolved_dataset_dir,
        dataset_manifest=dataset_manifest,
        all_plays=plays,
        season=resolved_season,
        week=resolved_week,
        game_id=game_id,
        source=source,
        payload_schema_version=payload_schema_version,
        dataset_version=dataset_version,
        model_version=model_version,
    )

    embeddings = _build_embedding_frame(processed_plays=processed_plays)

    raw_games = selected_games.rename(columns={"team_context_id": "team_id"}).copy()
    raw_games["source"] = source
    raw_games["dataset_version"] = dataset_version
    raw_games["model_version"] = model_version
    raw_games["payload_schema_version"] = payload_schema_version

    raw_games_path = (
        resolved_lake_root
        / "raw"
        / source
        / str(resolved_season)
        / str(resolved_week)
        / game_id
        / "games.parquet"
    )
    processed_plays_path = (
        resolved_lake_root
        / "processed"
        / "plays"
        / str(resolved_season)
        / str(resolved_week)
        / game_id
        / "plays.parquet"
    )
    tracking_path = (
        resolved_lake_root
        / "processed"
        / "tracking"
        / str(resolved_season)
        / str(resolved_week)
        / game_id
        / "tracking.parquet"
    )
    embedding_path = (
        resolved_lake_root
        / "embeddings"
        / model_version
        / str(resolved_season)
        / f"{game_id}.parquet"
    )

    _write_parquet(raw_games, raw_games_path)
    _write_parquet(processed_plays, processed_plays_path)
    _write_parquet(tracking, tracking_path)
    _write_parquet(embeddings, embedding_path)

    manifest_version = _manifest_version(dataset_version, resolved_season, resolved_week, game_id)
    manifests = (
        _write_manifest(
            lake_root=resolved_lake_root,
            dataset="raw_games",
            dataset_version=manifest_version,
            schema_version=schema_version,
            source=source,
            season=resolved_season,
            week=resolved_week,
            game_id=game_id,
            model_version=model_version,
            payload_schema_version=payload_schema_version,
            row_count=len(raw_games.index),
            checksum=_sha256(raw_games_path),
            created_by=created_by,
            source_uri=resolved_dataset_dir.as_posix(),
            artifact_path=raw_games_path.relative_to(resolved_lake_root),
        ),
        _write_manifest(
            lake_root=resolved_lake_root,
            dataset="processed_plays",
            dataset_version=manifest_version,
            schema_version=schema_version,
            source=source,
            season=resolved_season,
            week=resolved_week,
            game_id=game_id,
            model_version=model_version,
            payload_schema_version=payload_schema_version,
            row_count=len(processed_plays.index),
            checksum=_sha256(processed_plays_path),
            created_by=created_by,
            source_uri=resolved_dataset_dir.as_posix(),
            artifact_path=processed_plays_path.relative_to(resolved_lake_root),
        ),
        _write_manifest(
            lake_root=resolved_lake_root,
            dataset="processed_tracking",
            dataset_version=manifest_version,
            schema_version=schema_version,
            source=source,
            season=resolved_season,
            week=resolved_week,
            game_id=game_id,
            model_version=model_version,
            payload_schema_version=payload_schema_version,
            row_count=len(tracking.index),
            checksum=_sha256(tracking_path),
            created_by=created_by,
            source_uri=resolved_dataset_dir.as_posix(),
            artifact_path=tracking_path.relative_to(resolved_lake_root),
        ),
        _write_manifest(
            lake_root=resolved_lake_root,
            dataset="play_embeddings",
            dataset_version=manifest_version,
            schema_version=schema_version,
            source=source,
            season=resolved_season,
            week=resolved_week,
            game_id=game_id,
            model_version=model_version,
            payload_schema_version=payload_schema_version,
            row_count=len(embeddings.index),
            checksum=_sha256(embedding_path),
            created_by=created_by,
            source_uri=resolved_dataset_dir.as_posix(),
            artifact_path=embedding_path.relative_to(resolved_lake_root),
        ),
    )

    return GameIngestArtifacts(
        season=resolved_season,
        week=resolved_week,
        game_id=game_id,
        lake_root=resolved_lake_root,
        manifest_paths=manifests,
    )


def backfill_season(
    *,
    season: int,
    dataset_dir: str | Path | None = None,
    lake_root: str | Path | None = None,
    source: str = "nfl_big_data_bowl",
    payload_schema_version: str = "0.0.1",
    schema_version: str = "0.0.1",
    created_by: str = "data-workstream-phase1",
) -> SeasonIngestSummary:
    """Ingest and validate every game for one season into canonical lake paths."""

    resolved_dataset_dir = (
        Path(dataset_dir).resolve() if dataset_dir is not None else default_curated_fixture_dir()
    )
    resolved_lake_root = (
        Path(lake_root).resolve() if lake_root is not None else default_lake_root()
    )

    dataset_manifest = _read_json(resolved_dataset_dir / "manifest.json")
    dataset_version = str(dataset_manifest["dataset_version"])
    model_version = str(dataset_manifest["model_version"])

    games = _read_csv(resolved_dataset_dir / "games.csv")
    season_games = games[games["season"].astype(int) == season].copy()
    if season_games.empty:
        raise ValueError(f"Season '{season}' was not found in the curated fixture dataset.")

    ordered_game_ids = (
        season_games.sort_values(["week", "game_id"])["game_id"]
        .astype(str)
        .drop_duplicates()
        .tolist()
    )

    manifest_paths: list[Path] = []
    for game_id in ordered_game_ids:
        artifacts = ingest_game(
            game_id=game_id,
            season=season,
            dataset_dir=resolved_dataset_dir,
            lake_root=resolved_lake_root,
            source=source,
            payload_schema_version=payload_schema_version,
            schema_version=schema_version,
            created_by=created_by,
        )
        manifest_paths.extend(artifacts.manifest_paths)

    resilience = _read_csv(resolved_dataset_dir / "player_resilience.csv")
    stress = resilience.rename(columns={"team_context_id": "team_id"}).copy()
    stress["source"] = source
    stress["season"] = season
    stress["week"] = 0
    stress["game_id"] = "season"
    stress["play_id"] = "season"
    stress["frame_id"] = pd.NA
    stress["player_id"] = stress["nfl_id"].astype(str)
    stress["model_version"] = model_version
    stress["dataset_version"] = dataset_version
    stress["payload_schema_version"] = payload_schema_version
    stress = _ensure_join_keys(stress, nullable_join_keys={"frame_id"})

    if (stress["samples"] < 0).any():
        raise ValueError("Player stress rows contain negative sample counts.")
    if ((stress["resilience_score"] < 0) | (stress["resilience_score"] > 1)).any():
        raise ValueError("Player stress rows contain resilience scores outside [0, 1].")

    stress_path = (
        resolved_lake_root
        / "processed"
        / "player_stress"
        / model_version
        / str(season)
        / "0"
        / "season"
        / "player_stress.parquet"
    )
    _write_parquet(stress, stress_path)

    stress_manifest_version = _manifest_version(dataset_version, season, 0, "season")
    stress_manifest = _write_manifest(
        lake_root=resolved_lake_root,
        dataset="processed_player_stress",
        dataset_version=stress_manifest_version,
        schema_version=schema_version,
        source=source,
        season=season,
        week=0,
        game_id="season",
        model_version=model_version,
        payload_schema_version=payload_schema_version,
        row_count=len(stress.index),
        checksum=_sha256(stress_path),
        created_by=created_by,
        source_uri=resolved_dataset_dir.as_posix(),
        artifact_path=stress_path.relative_to(resolved_lake_root),
    )
    manifest_paths.append(stress_manifest)

    return SeasonIngestSummary(
        season=season,
        ingested_games=len(ordered_game_ids),
        lake_root=resolved_lake_root,
        manifest_paths=tuple(manifest_paths),
    )
